global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 